chat/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('', views.messages_page,name='messages_page'),
    path('start-chat/<int:freelancer_id>/', views.start_chat, name='start_chat'),
]

jobs/urls.py
from django.urls import path
from . import views
from .views import (
    register,
    login_view,
    logout,
    profile,
    edit_profile,
    post_job,
    company_dashboard,
    apply_to_job,
    view_job,
    view_jobs,
    see_applications,
)
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView, TokenVerifyView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

urlpatterns = [
    path('', views.home, name='home'),
    path('register/', register, name='register'),
    path('login/', login_view, name='login'),
    path('logout/', logout, name='logout'),
    path('password_reset/', PasswordResetView.as_view(template_name='sign/password_reset_form.html'), name='password_reset'), 
    path('password_reset/done/', PasswordResetDoneView.as_view(template_name='sign/password_reset_done_form.html'), name='password_reset_done'), 
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name='sign/password_reset_confirm.html'), name='password_reset_confirm'), 
    path('reset/done/', PasswordResetCompleteView.as_view(template_name='sign/password_reset_complete.html'), name='password_reset_complete'),
    path('profile/', profile, name='profile'),
    path('edit_profile/<str:role>/', edit_profile, name='edit_profile'),
    path('post_job/', post_job, name='post_job'),
    path('edit_job/<int:job_id>/', views.edit_job, name='edit_job'),
    path('edit_skills/', views.edit_skills, name='edit_skills'),
    path('company_dashboard/',company_dashboard,name='company_dashboard'),
    path('find_freelancer/', views.find_freelancer, name='find_freelancer'),
    path('jobs/', views.view_jobs, name='view_jobs'),
    path('job/<int:job_id>/', view_job, name='view_job'),
    path('job/<int:job_id>/apply/', views.apply_to_job, name='apply_to_job'),
    # path('job/<int:job_id>/submit_work/', views.submit_work, name='submit_work'), 
    path('view_submission/<int:submission_id>', views.view_submission, name='view_submission'), 
    path('accept_submission/<int:submission_id>/', views.accept_submission, name='accept_submission'),
    path('job/<int:job_id>/select_freelancer/<int:application_id>/', views.select_freelancer, name='select_freelancer'),
    path('post_project/', views.post_project, name='post_project'),
    path('freelancer/<int:freelancer_id>/', views.view_freelancer, name='view_freelancer'),
    path('apply_to_job/<int:job_id>/', apply_to_job, name='apply_to_job'),
    path('applications/', see_applications, name='applications'),
    path('active_projects/', views.active_projects, name='active_projects'),
    path('job_search/', views.home, name='job_search'),
    path('rate/<int:job_id>/<int:recipient_id>/', views.rate, name='rate'),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/token/verify/', TokenVerifyView.as_view(), name='token_verify'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

parttimers/urls.py
from django.contrib import admin
from django.urls import include, path
from jobs import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('jobs.urls')),
    path('chat/', include('chat.urls')),
] 

jobs/models.py
import datetime
import re
from django import forms
from django.forms.widgets import DateInput
from django.core.exceptions import ValidationError
from django.contrib.postgres.fields import ArrayField
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.utils import timezone
from django.db import models
from django.shortcuts import get_object_or_404, render
from django.db.models import Avg
from .validators import validate_is_pdf
from ckeditor.fields import RichTextField


class CustomUserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError('The Email field must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        return self.create_user(email, password, **extra_fields)


class CustomUser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True, max_length=255)
    username= models.CharField(max_length=30, blank=True)
    first_name=models.CharField(max_length=30, blank=True)
    last_name=models.CharField(max_length=30, blank=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    date_joined = models.DateTimeField(auto_now_add=True)

    objects = CustomUserManager()

    USERNAME_FIELD = 'email'
    EMAIL_FIELD = 'email'
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.email

    def get_short_name(self):
        return self.first_name
    
    def get_rating(self): 
        avg_rating = self.recipient_ratings.aggregate(Avg('rating'))['rating__avg'] 
        if avg_rating is not None: 
            return round(avg_rating, 2) 
        else: 
            return None
    
    def save(self, *args, **kwargs):
        if not self.username:
            self.username = self.first_name +" "+ self.last_name
        super().save(*args, **kwargs)


class Company(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    field = models.CharField(max_length=30, blank=True)
    description = RichTextField(blank=True, null=True)
    logo = models.ImageField(default='default_picture.png', upload_to='company_profile_images', blank=True)
    skills = ArrayField(models.CharField(null=True, blank=True, max_length=30), null=True, blank=True)
    instagram_link = models.URLField(max_length=200, blank=True) 
    linkedin_link = models.URLField(max_length=200, blank=True) 
    facebook_link = models.URLField(max_length=200, blank=True) 
    website_link = models.URLField(max_length=200, blank=True)
    created_at = models.DateTimeField(default=timezone.now)

    def get_num_ratings(self):
        return Rating.objects.filter(recipient=self.user).count()

    def get_rating(self):
        return self.user.get_rating()
    
    def get_num_jobs_posted(self):
        return Job.objects.filter(company=self).count()

    def get_member_since(self):
        return self.created_at.strftime("%Y")

    def save(self, *args, **kwargs):
        if not self.name:
            self.name = self.user.first_name
        if not self.field:
            self.field = self.user.last_name
        super().save(*args, **kwargs)

# class Skill(models.Model): 
#     name = models.CharField(default='m', max_length=50) 

#     def __str__(self):
#         return self.name


# class Freelancer(models.Model):
#     user = models.OneToOneField(CustomUser, on_delete=models.CASCADE) 
#     first_name = models.CharField(default='', max_length=20)
#     last_name = models.CharField(default='', max_length=20)
#     occupation = models.CharField(default='', max_length=20)
#     level = models.CharField(default='', max_length=15)
#     bio = RichTextField(blank=True, null=True)
#     photo = models.ImageField(default='default_picture.png', upload_to='freelancer_profile_images', blank=True)
#     skills = models.ManyToManyField(Skill) 
#     education_university = models.CharField(default='', max_length=30)
#     education_specialization = models.CharField(default='', max_length=30)
#     education_year_of_study = models.CharField(default='', max_length=20)
#     experience_position = models.CharField(default='', max_length=30)
#     experience_company_name = models.CharField(default='', max_length=30)
#     experience_work_duration = models.CharField(default='', max_length=20)
#     experience_description = models.TextField(default='')
#     created_at = models.DateTimeField(auto_now_add=True)
#     portfolio_link = models.URLField(blank=True)

#     def get_rating(self):
#         return self.user.get_rating()

class Skill(models.Model):
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.name

# class Position(models.Model):
#     name = models.CharField(default='', null=True, max_length=25) 
    
#     def __str__(self):
#         return self.name

class Freelancer(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE) 
    first_name = models.CharField(default='', max_length=20)
    last_name = models.CharField(default='', max_length=20)
    occupation = models.CharField(default='', max_length=20)
    level = models.CharField(default='', max_length=15)
    bio = RichTextField(blank=True, null=True)
    photo = models.ImageField(default='default_picture.png', upload_to='freelancer_profile_images', blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    portfolio_link = models.URLField(blank=True)
    skills = models.ManyToManyField(Skill, blank=True)

    def get_num_ratings(self):
        return Rating.objects.filter(recipient=self.user).count()

    def get_rating(self):
        return self.user.get_rating()
    
    def save(self, *args, **kwargs):
        if not self.first_name:
            self.first_name = self.user.first_name
        if not self.last_name:
            self.last_name = self.user.last_name
        super().save(*args, **kwargs)


class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    freelancer = models.ForeignKey(Freelancer, on_delete=models.CASCADE)
    link = models.URLField()
    platform = models.CharField(max_length=50)

    
class Education(models.Model):
    freelancer = models.ForeignKey(Freelancer, on_delete=models.CASCADE, related_name='educations')
    university = models.CharField(max_length=30)
    specialization = models.CharField(max_length=30)
    year_of_study = models.CharField(max_length=20)


class Experience(models.Model):
    freelancer = models.ForeignKey(Freelancer, on_delete=models.CASCADE, related_name='experiences')
    position = models.CharField(max_length=30)
    company_name = models.CharField(max_length=30)
    work_duration = models.CharField(max_length=20)
    description = models.TextField()


class Category(models.Model):
    name = models.CharField(max_length=255) 
    
    def __str__(self):
        return self.name


class DateField(forms.DateField):
    input_formats = ['%d.%m.%Y']
    widget = forms.DateInput(format='%d.%m.%Y')

    def validate(self, value):
        super().validate(value)
        if value is not None and isinstance(value, (str, bytes)) and not re.match(r"^\d{1,2}\.\d{2}\.\d{4}$", value):
            raise ValidationError("Invalid date format. Use dd.mm.yyyy.")


class Job(models.Model): 
    title = models.CharField(max_length=255) 
    description = RichTextField(blank=True, null=True) 
    file = models.FileField(upload_to='company_files/', validators=(validate_is_pdf,), blank=True) 
    category = models.ForeignKey(Category, on_delete=models.CASCADE) 
    skills = models.ManyToManyField(Skill, blank=True) 
    position = models.CharField(default='', max_length=20) 
    created_at = models.DateTimeField(auto_now_add=True) 
    company = models.ForeignKey(Company, on_delete=models.CASCADE) 
    is_active = models.BooleanField(default=True) 
    salary = models.PositiveIntegerField(null=True, blank=True) 
    timeline = models.DateField() 
    freelancer = models.ForeignKey(Freelancer, on_delete=models.SET_NULL, blank=True, null=True) 
    status = models.CharField(max_length=255, default='pending')

    def get_timeline_display(self):
        return self.timeline.strftime("%d.%m.%Y")
    
    def freelancer_has_applied(self, freelancer):
        return JobApplication.objects.filter(job=self, freelancer=freelancer).exists()
    

class JobApplication(models.Model): 
    job = models.ForeignKey(Job, on_delete=models.CASCADE) 
    freelancer = models.ForeignKey(Freelancer, on_delete=models.CASCADE) 
    status=models.CharField(max_length=20,default='pending')


class Submission(models.Model): 
    job = models.ForeignKey(Job, on_delete=models.CASCADE) 
    freelancer = models.ForeignKey(Freelancer, on_delete=models.CASCADE) 
    link = models.URLField(max_length=255) 
    file = models.FileField(upload_to='freelancer_files/', blank=True, null=True)
    submitted_at = models.DateTimeField(auto_now_add=True) 
    order = models.IntegerField(default=0)  
    STATUS_CHOICES = [ 
        ('pending', 'Pending'), 
        ('accepted', 'Accepted'), 
        ('rejected', 'Rejected'), 
    ] 
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='pending') 
 
    def __str__(self): 
        return f'Submission for "{self.job.title}" by {self.freelancer.user.username}'


class Rating(models.Model): 
    RATING_CHOICES = ( 
        (1, '1 star'), 
        (2, '2 stars'), 
        (3, '3 stars'), 
        (4, '4 stars'), 
        (5, '5 stars'), 
    ) 

jobs/templates/modals/post_project.html
<!-- <div class="modal fade" id="create-project-modal" tabindex="-1" role="dialog" aria-labelledby="create-project-modal-label" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="create-project-modal-label">Create Project</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ project_form.as_p }}
                    <button type="submit" class="btn btn-primary">Create</button>
                </form>
            </div>
        </div>
    </div>
</div> -->

<div class="project-modal" id="project-modal-id">
    <span title="Close" class="close font-color-black font-size-40 font-weight-700">&times;</span>
    <h1>Upload new project</h1>
    {% if project_form %}
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ project_form.as_p }}
            <button type="submit" class="btn btn-primary">Create</button>
        </form>
    {% endif %}
    
</div>

jobs/templates/modals/rating.html
<div class="container rating-container">
    <p class="rating-icon"><i class="fa-solid fa-comments rating-icon"></i></p>
    <h1 class="rating-h1">Please, rate your experience</h1>
    <form method="post">
        {% csrf_token %}
        <div class="rating-container-form">
            <h2 class="rating-h2">Buy again or recommend</h2>
            <p class="rating-p">Would you recommend this freelancer? Please, rate service by stars</p>
            <div class="rating-form">
                <input type="radio" name="rating" value="5" required="" id="id_rating_5">
                <label for="id_rating_5" class="fa-solid fa-star"></label>
                <input type="radio" name="rating" value="4" required="" id="id_rating_4">
                <label for="id_rating_4" class="fa-solid fa-star"></label>
                <input type="radio" name="rating" value="3" required="" id="id_rating_3">
                <label for="id_rating_3" class="fa-solid fa-star"></label>
                <input type="radio" name="rating" value="2" required="" id="id_rating_2">
                <label for="id_rating_2" class="fa-solid fa-star"></label>
                <input type="radio" name="rating" value="1" required="" id="id_rating_1">
                <label for="id_rating_1" class="fa-solid fa-star"></label>
            </div>
            <h2 class="rating-h2">Wat was like working with this freelancer?</h2>
            <p class="rating-p">Comment your experience with this freelancer</p>
            <textarea name="comment" cols="40" rows="3" id="id_comment" placeholder="Text" cl></textarea>
        </div>
        <div class="rating-btn"><button type="submit">Send</button></div>
    </form>
</div>

jobs/templates/modals/submit_work.html
<section class="submit-work">
    <span title="Close" class="close font-color-black font-size-40 font-weight-700">&times;</span>
    <h1 class="font-style-normal font-weight-600 font-size-25 font-color-main-color" style="margin-bottom: 1rem;">{{ application.job.title }}</h1>
    <p class="font-style-normal font-weight-400 font-size-20 font-color-main-color">Status</p>
    <p class="font-style-normal font-weight-400 font-color-e9a31b font-size-18 opacity-07" style="margin-bottom: 1rem;">
        {% if application.job.status == 'progress' %}
            In Progress
        {% elif application.job.status == 'pending_review' %}
            On Review
        {% endif %}
    </p> 
    <form class="display-flex flex-direction-column" method="POST" enctype="multipart/form-data">  
        {% csrf_token %}  
        <div class="file-add-area display-f-c-c">
            <input type="file" name="file" id="id_file">
            <label for="id_file" class="custom-file-label display-flex flex-direction-column align-items-center justify-content-center">
                <i class="fa-solid fa-upload font-size-24"></i>
                <p>Click to upload your project  </p>
            </label>
        </div>
        
        <span class="display-flex align-items-center justify-content-sb">
            <div class="horizontal-line"></div>
            <p class="font-style-normal font-weight-400 font-color-main-color font-size-25 opacity-0">OR</p>
            <div class="horizontal-line"></div>
        </span>
        <div>
            <label for="link" class="font-style-normal font-weight-500 font-color-042552 font-size-16 opacity-07">Paste your link to your project or cv</label>
            <input class="link-inp font-size-16" type="url" name="link" maxlength="255" id="id_link" placeholder="Link to project">
        </div>
        
        <!-- {{ form.as_p }}   -->
        <input type="hidden" name="job_id" value="{{ application.job.id }}"> 
        <div>
            <button type="submit" class="btn btn-btn font-style-normal font-weight-500 font-size-16 font-color-white" style="padding: 0.2rem 1.5rem;">Submit Work</button>   
        </div>
        
    </form>
</section>

jobs/templates/modals/view_portfolio.html
<div class="portfolio-item-modal">
    <div class="display-flex flex-direction-column" style="row-gap: 1rem;">
        <h3 class="font-style-normal font-weight-600 font-size-30 font-color-main-color">{{ profile.first_name }}'s portfolio</h3>
        <div>
            <h4 class="font-style-normal font-weight-600 font-size-25 font-color-main-color">Title</h4>
            <p class="font-style-normal font-weight-600 font-size-22 font-color-042552">{{ project.title }}</p>
        </div>
        <div>
            <h4 class="font-style-normal font-weight-600 font-size-25 font-color-main-color">Description</h4>
            <p class="font-style-normal font-weight-600 font-size-20 font-color-042552">{{ project.description }}</p>
        </div>
        <div>
            <p class="font-style-normal font-weight-600 font-size-16 font-color-042552 opacity-07" style="margin-bottom: 0.7rem;" >Click to the link</p>
            <a class="text-decoration-no profile-skill font-color-black" href="{{ project.link }}">{{ project.platform }}</a>
        </div>
    </div>
</div>

jobs/templates/modals/view_submission.html
<section class="view-submission"> 
    
    <span title="Close" class="close font-color-black font-size-40 font-weight-700">&times;</span> 
    <h1 class="font-style-normal font-weight-600 font-size-25 font-color-main-color" style="margin-bottom: 1rem;">{{ application.job.title }}</h1>
    <p class="font-style-normal font-weight-400 font-size-20 font-color-main-color">Status</p>
    {% if application.job.status == 'progress' %}
        <p class="font-style-normal font-weight-400 font-color-e9a31b font-size-18 opacity-07" style="margin-bottom: 1rem;">In Progress</p>
    {% elif application.job.status == 'pending_review' %}
        <p class="font-style-normal font-weight-400 font-color-e9a31b font-size-18 opacity-07" style="margin-bottom: 1rem;">On Review</p>
    {% elif application.job.status == 'completed' %}
        <p class="font-style-normal font-weight-400 font-color-379909 font-size-18 opacity-07" style="margin-bottom: 1rem;">Done</p>
    {% endif %}

    {% if application.job.status == 'pending_review' %}
    <form class="display-flex flex-direction-column" method="POST" enctype="multipart/form-data"> 
        {% csrf_token %}  

        <div class="file-download-submission">
            {% if submission.file %}
                {% if submission.file.url %}
                    <a href="{{ submission.file.url }}" target="_blank" class="display-sb-c text-decoration-no font-size-16 font-color-042552 opacity-07" style="padding: 1rem 1rem;">
                        {{ submission.file }}
                        <i class="fa-solid fa-download"></i>
                    </a>
                {% endif %}
                {% else %}
                <div class="display-sb-c" style="padding: 1rem 1rem;">
                    <p class="display-sb-c font-size-16 font-color-042552 opacity-07">No file</p>
                    <i class="fa-solid fa-download"></i>
                </div>
            {% endif %}

        </div>
        <span class="display-flex align-items-center justify-content-sb">
            <div class="horizontal-line"></div>
            <p class="font-style-normal font-weight-400 font-color-main-color font-size-25 opacity-0">OR</p>
            <div class="horizontal-line"></div>
        </span>

        <div class="file-download-submission">
            {% if submission.link %}
                <a href="{{ submission.link }}" class="font-style-normal font-weight-400 font-color-042552 opacity-07 font-size-16 truncated-link" style="padding: 1rem 1rem;">{{ submission.link }}</a> 
            {% else %}
                <p class="font-style-normal font-weight-400 font-color-042552 opacity-07 font-size-16" style="padding: 1rem 1rem;">There's no link</p>
            {% endif %}
        </div>
        

        <input type="hidden" name="submission_id" value="{{ submission.id}}"> 
        <input type="hidden" name="action" value="accept"> 
        <div>
            <button type="submit" class="btn btn-btn font-style-normal font-weight-500 font-size-16 font-color-white" style="padding: 0.2rem 1.5rem;">Accept Work</button>  
        </div>
    </form> 

    {% else %}
        <section class="display-flex flex-direction-column">
            <div class="file-download-submission">
                {% if submission.file %}
                    {% if submission.file.url %}
                        <a href="{{ submission.file.url }}" target="_blank" class="display-sb-c text-decoration-no font-size-16 font-color-042552 opacity-07" style="padding: 1rem 1rem;">
                            {{ submission.file }}
                            <i class="fa-solid fa-download"></i>
                        </a>
                    {% endif %}
                    {% else %}
                    <div class="display-sb-c" style="padding: 1rem 1rem;">
                        <p class="display-sb-c font-size-16 font-color-042552 opacity-07">No file</p>
                        <i class="fa-solid fa-download"></i>
                    </div>
                {% endif %}
    
            </div>
            <span class="display-flex align-items-center justify-content-sb">
                <div class="horizontal-line"></div>
                <p class="font-style-normal font-weight-400 font-color-main-color font-size-25 opacity-0">OR</p>
                <div class="horizontal-line"></div>
            </span>
    
            <div class="file-download-submission">
                {% if submission.link %}
                    <a href="{{ submission.link }}" class="font-style-normal font-weight-400 font-color-042552 opacity-07 font-size-16 truncated-link" style="padding: 1rem 1rem;">{{ submission.link }}</a> 
                {% else %}
                    <p class="font-style-normal font-weight-400 font-color-042552 opacity-07 font-size-16" style="padding: 1rem 1rem;">There's no link</p>
                {% endif %}
            </div>
        </section>
    {% endif %}
</section>